[package]
label = "atom-nix"
version = "0.4.3"

[package.meta]
tags = ["atom:composer"]
description = "A purpose built, unopinionated, and performant module system for Nix code."

[compose.as]
nix = "."
